### ISSUE TITLE
[Page] Default spacing/page widths

### ISSUE THREAD

**Issue by LeaVerou** [shoelace-style/webawesome#245]
https://webawesome-git-next-font-awesome.vercel.app/docs/components/page#how-to-apply-spacing-to-your-layout

> The layout component does not apply spacing for you. You can apply the appropriate paddings or margins directly to the elements you slot in to fine tune your spacing needs.
> When using <wa-page>, make sure to zero out all paddings and margins on <html> and <body>, otherwise you may see unexpected gaps. 

As discussed yesterday with @claviska and @KonnorRogers, ideally we want `<wa-page>` to add nice spacing etc so that simply using it immediately yields benefits, and users can always override them. We'd need @lindsaym-fa's help about what these defaults should look like.

This would also mean adding something like this to Applied CSS (which we currently recommend people add manually):

```css
:is(html, body):has(wa-page) {
  min-height: 100%;
  height: 100%;
  padding: 0;
  margin: 0;
}
```

I’d be inclined to tag this high priority since it _really_ diminishes the onboarding experience for `<wa-page>` but if you folks disagree feel free to change it!

**Comment by lindsaym-fa** [comment]
I collected a handful of screenshots here: https://www.figma.com/board/lIVFZrhXIJpfZmiho5wQrK/Page-Layout-Samples?node-id=0-1&t=JJCVroMw46rmr6WP-1

Some general observations, none very surprising:
- A lot of headers use `flex` with `justify-content: space-between`
- Banners and subheaders typically have a smaller footprint than headers in addition to smaller font sizes
- Main sections have the largest spacing relative to other sections
- Sites with a navigation section seem to prefer using the equivalent of `main-footer` for their site footer. `main-footer` and `footer` may be interchangeable for full-width sites.
- Footers vary widely with either a very large footprint or a very smaller footprint. Large footprints seem more common.

This left me wondering: should we also have default `flex` properties and even `font-size`s for each section? There are enough sites that use their standard font size for their banners, subheaders, and footers that I'm less comfortable imposing the opinion that these should be smaller by default, but curious if anyone else has feelings about this. Default `flex` layouts could be a great boost, though. I'll include defaults for this in the list below, if we agree it's predictable enough to be a help rather than a hindrance.

Here's what I'm thinking as a blind first pass (these terms aren't meant to dictate the actual CSS implementation, so pardon the overlap):

- `banner`
  - Layout: inline, center justified
  - Padding: `--wa-space-s` block, `--wa-space-m` inline
  - Gap: `--wa-space-m`
- `header`
  - Layout: inline, justified space-between
  - Padding: `--wa-space-m`
  - Gap: `--wa-space-m`
- `subheader`
  - Layout: inline, start justified
  - Padding: `--wa-space-s` block, `--wa-space-m` inline
  - Gap: `--wa-space-m`
- `navigation-header`
  - Layout: block, start justified
  - Padding: `--wa-space-m`
  - Gap: `--wa-space-m`
- `navigation`/`menu`
  - Layout: block, start justified
  - Padding: `--wa-space-m`
  - Gap: `--wa-space-m`
- `navigation-footer`
  - Layout: block, start justified
  - Padding: `--wa-space-m`
  - Gap: `--wa-space-m`
- `main-header`
  - Layout: inline, justified space-between
  - Padding: `--wa-space-m` block, `--wa-space-3xl` inline
  - Gap: `--wa-space-m`
- `main`
  - Layout: block, start justified
  - Padding: `--wa-space-3xl`
  - Gap: `--wa-space-3xl`
- `main-footer`
  - Layout: inline, justified space-between
  - Padding: `--wa-space-3xl`
  - Gap: `--wa-space-xl`
- `aside`
  - Layout: block, start justified
  - Padding: `--wa-space-m`
  - Gap: `--wa-space-m`
- `footer`
  - Layout: inline, justified space-between
  - Padding: `--wa-space-3xl`
  - Gap: `--wa-space-xl`
