### ISSUE TITLE
Docs for Applied Styles

### ISSUE THREAD

**Issue by claviska** [shoelace-style/webawesome#80]
Applied styles were added a while ago, but they were never documented. A "style guide" was added to demo various styles at `/experimental/style-guide` as part of this.

- [x] Document what applied styles are and how to use them with copy/pastable code
- [x] Add native form styles to look more like WA form controls #217

**Comment by claviska** [comment]
We previously discussed this with Dave and he has agree to make Appied Styles part of WA free!

**Comment by lindsaym-fa** [comment]
A note — Our native styles can be overridden both by standard CSS properties _and_ the same custom properties used by our components. I think we ought to highlight this in the docs since it simplifies overriding styles for both the component and native element, e.g.:
```
button.wa-brand,
wa-button[variant='brand'] {
  --background-color: violet;
}
```

**Comment by LeaVerou** [comment]
@lindsaym-fa Agreed that's a good tip. We should probably use a different property in the example, since we're slowly removing the custom properties mirroring native ones (see #259)

Btw I think at this point we have enough docs that we can close this. We can always open one-off issues for specific issues with the docs.
